### ISSUE TITLE
Angular & Typescript Updates

### ISSUE THREAD

**Issue by kellscode** [carbon-design-system/carbon-web-components#1012]
### Description

My project was working fine in Angular 10 Typescript 3.9.10, but upgrading to Angular 11 Typescript 4.0.2 results in the following message
`Error: node_modules/carbon-web-components/es/components/input/input.d.ts:638:9 - error TS2611: 'value' is defined as a property in class '{ _getValidityMessage(state: string): any; _testValidity(): string; invalid: boolean; required: boolean; requiredValidityMessage: string; validityMessage: string; value: string; checkValidity(): boolean; ... 242 more ...; focus(options?: FocusOptions): void; } & { ...; } & LitElement', but is overridden here in 'BXInput' as an accessor.

638     get value(): string;`

I found that typescript 4.0. Beta's breaking change refers to this exact error [(Properties Overridding Accessors and vice versa is an Error)](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#breaking-changes)

But the error coming from carbon-web-components isn't resolvable. I am unable to run my application due to this error.

### Component(s) impacted

I can't run the application due to the above error. Following is my package versions:

Angular CLI: 11.2.19
Node: 14.19.3
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cdk                    10.2.4
@angular/cli                    11.2.19
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.5.3
typescript                      4.0.2

### Browser

Chrome

### Carbon Web Components version

v.1.21.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

angular

### CodeSandbox example

unable to re-create issue outside of project

### Steps to reproduce the issue (if applicable)

I was unable to re-create the issue outside of the project

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by abdonrd** [comment]
Maybe related? https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9044
